### ISSUE TITLE
faltou acento no ola

### ISSUE THREAD

**Issue by renanmoreira17** [Tesla-UFMG/repo-teste#3]
https://github.com/Tesla-UFMG/repo-teste/blob/5c44211606e71f9c66eb8b9823c56301c2fb27bb/main.c#L8

coloca acento no olá

**Comment by renanmoreira17** [comment]
precisa mesmo do acento?

**Comment by Cortella** [comment]
deu merda

**Comment by renanmoreira17** [comment]
problema resolvido
